language: java
jdk:
  - oraclejdk8
env:
  global:
    # created using `travis encrypt -r asciidoctor/asciidoctor.org`
    # GIT_N=<git name> GIT_E=<git email> GH_U=<github username> GH_T=<github oauth token>
    secure: Wa+WTnxtCvYtH5xrYfVkUD47TGZHZerRs0Nmq2OwXccFJ/H5NAQKWvQAH75p+byMGMNrMkrcejGZfRrCiHr8aMeN5J0aNTlBwVGezNhvu+U4jQBzBQsUPxiXg+PhiHtBxUaODrEXdbFXot6KzOIX+Tlnbzz3zKltJI4hdtkbFB4=
    # makes jruby unvocations a bit faster
    MAVEN_OPTS="-Djruby.compile.mode=OFF -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
branches:
  only:
    - master
script: rake travis
