#coding: UTF-8
#but everywhere I look they say UTF-8 is the default
name: "Patrik Duditš"
title: Patrik Duditš - Development blog
org: Organization
base_url: ''
asciidoctor:
  :attributes:
    source-highlighter: coderay
profiles:
  development:
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://pdudits.github.io/blog
    disqus_developer: false
    compass_output_style: :compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: gh-pages    